PR for $isValidObject (#580)
* Update modifyRolePerms.js

fixed TypeError: arrayPerms.add is not a function maybe

* fixed it cuz i broke it even worse should be better now tho

* was forced to remove commits

* Fixed actually

* remove not needed var

* fixed function

---------

Co-authored-by: Fafa <87046111+Faf4a@users.noreply.github.com>